name: test
on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2

      - run: python3 --version

      - id: test-action
        uses: ./
        with:
          python-version: '3.10'
          netrc-token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo venv dir ${{ steps.test-action.outputs.venv-dir }}
        shell: bash

      - run: python3 --version

      - run: echo $ANSIBLE_PYTHON_INTERPRETER

      - run: ${{ steps.test-action.outputs.venv-dir }}/bin/ansible --version

      - name: testing commands
        run: |
           source ${{ steps.test-action.outputs.venv-dir }}/bin/activate
           ansible --version
