name: test
on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: python3 --version

      - name: ansible-action
        id: test-action
        uses: ./
        with:
          python-version: '3.10'
          python-requirements: ./requirements.txt
          netrc-token: ${{ secrets.GITHUB_TOKEN }}

      - run: python3 --version

      - run: echo $ANSIBLE_PYTHON_INTERPRETER

      - name: testing ansible bin output
        run: ${{ steps.test-action.outputs.ansible-bin }} --version

      - name: testing separate commands source
        run: source ${{ steps.test-action.outputs.activate-script }}

      - name: testing separate commands ansible
        run: ansible --version

      - name: testing ansible galaxy install
        run: ansible-galaxy collection install community.kubernetes

      - name: check netrc creation
        run: cat ~/.netrc
